number:
  - platform: template
    name: "${board_name} LED Brightness"    # number.domofon_led_brightness in system
    icon: "mdi:led-on"
    id: led_brightness
    optimistic: true
    restore_value: true
    initial_value: 7
    min_value: 0
    max_value: 10
    step: 1
    on_value:
      then:
        if:
          condition:
            light.is_on: rgb_led              # missing
          then:
            light.control:                    # missing
              id: rgb_led
              brightness: !lambda "return x > 0 ? x / 10 : 0.01;"
