<<<<<<< HEAD
title: Home Assistant - сервер
views:
  - !include lovelace/01_system.yaml
=======
title: Home Assistant - сервер
views:
  - !include lovelace/01_system.yaml
>>>>>>> 6d6a0ed04d4a624e651d2332d2e651b7dbbd95e1
