<<<<<<< HEAD
# не работает корректно. оставляет только первую позицию.
- platform: command_line
  name: shopping_list
  command: "jq -r '.[] | select(.complete==false) | .name' .shopping_list.json"
    
#  - platform: command_line
#  name: shopping_list_number
=======
# не работает корректно. оставляет только первую позицию.
- platform: command_line
  name: shopping_list
  command: "jq -r '.[] | select(.complete==false) | .name' .shopping_list.json"
    
#  - platform: command_line
#  name: shopping_list_number
>>>>>>> 6d6a0ed04d4a624e651d2332d2e651b7dbbd95e1
#  command: "jq length .shopping_list.json"