- platform: template
  sensors:
    version:
      friendly_name: 'Последняя версия - '
      value_template: '{{ states.binary_sensor.updater.attributes["newest_version"] }}'

- platform: version
  name: current_ha
  scan_interval: 1800

- platform: systemmonitor                   # https://www.home-assistant.io/components/systemmonitor/
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
# ifconfig -a | sed 's/[ \t].*//;/^$/d'


#### https://www.home-assistant.io/components/filesize/
#- platform: filesize
#  file_paths:
#    - /config/home-assistant_v2.db

# Maria DB size
- platform: sql
  db_url: !secret db_url
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="hassdb" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB

- platform: uptime
  name: online

- platform: template
  sensors:
       
    online_custom:
       friendly_name: "Home Assistant в онлайне -"
       value_template: >
         {% set uptime = as_timestamp (now()) -as_timestamp(states('sensor.online')) | int %}
         {% set minutes = (( uptime % 3600) / 60) | int %}
         {% set hours = ((uptime % 86400) / 3600) | int %}
         {% set days = (uptime / 86400) | int %}

           {% if uptime < 1 %}
             Меньше минуты
           {% else %}
             {% if days > 0 %}
               {{ days }} д.
             {% endif %}
             {% if hours > 0 %}
               {% if days > 0 %}
                 {{ ' ' }}
               {% endif %}
               {{ hours }} ч.
             {% endif %}
             {% if minutes > 0 %}
               {% if days > 0 or hours > 0 %}
                 {{ ' ' }}
               {% endif %}
                 {{ minutes }} мин.
             {% endif %}
           {% endif %}
       icon_template: mdi:clock
             
# Время с последней перезагрузки
    last_boot_custom:
      friendly_name: "Сервер в онлайне -"
      value_template: >
         {% set uptime = as_timestamp (now()) -as_timestamp(states('sensor.last_boot')) | int %}
         {% set minutes = (( uptime % 3600) / 60) | int %}
         {% set hours = ((uptime % 86400) / 3600) | int %}
         {% set days = (uptime / 86400) | int %}

           {% if uptime < 1 %}
             Меньше минуты
           {% else %}
             {% if days > 0 %}
               {{ days }} д.
             {% endif %}
             {% if hours > 0 %}
               {% if days > 0 %}
                 {{ ' ' }}
               {% endif %}
               {{ hours }} ч.
             {% endif %}
             {% if minutes > 0 %}
               {% if days > 0 or hours > 0 %}
                 {{ ' ' }}
               {% endif %}
                 {{ minutes }} мин.
             {% endif %}
           {% endif %}
      icon_template: mdi:clock



# https://www.home-assistant.io/integrations/cert_expiry
# alternative - https://community.home-assistant.io/t/sensor-to-show-expiry-date-of-ssl-certificate/13479/66
####  see package ssl_certificate_expiry.yaml
#sensor:
#- platform: cert_expiry
#  host: !secret cert_expiry_host
#  port: 88
# sensor.cert_expiry_timestamp_hellad_noip_me_88
            
#### if Zanzito programm is used on android ####
#- platform: mqtt
#  state_topic: "zanzito/adhtcone/battery_level"
#  name: "Andrey's HTC Battery"
#  unit_of_measurement: "%"
#  value_template: '{{ value_json.batt }}'
#- platform: template
#  sensors:
#    andreys_htc_battery_dynamic:
#      unit_of_measurement: '%'
#      entity_id: sensor.andreys_htc_battery
#      value_template: "{{ (states.sensor.andreys_htc_battery.state)|int|default('unknown') }}"
#      icon_template: >-
#        {% set battery_level = states('sensor.andreys_htc_battery')|int('unknown') %}
#        {% set battery_round = (battery_level|int / 10)|int * 10 %}
#        {% if battery_level == 'unknown' %}
#          mdi:battery-unknown
#        {% else %}
#          {% if battery_round >= 100 %}
#              mdi:battery
#          {% elif battery_round > 0 %}
#              mdi:battery-{{ battery_round }}
#          {% else %}
#            mdi:battery-alert
#          {% endif %}
#        {% endif %}
