# Description:
#   Example of how to restart MQTT broker from within Home Assistant.
#
# Written for:
#   @torn8o
#
# Components:
#   script
#   shell_command
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

################################################################
## Packages / Restart MQTT
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    script.restart_mqtt:
      friendly_name: "Restart MQTT Broker"
      icon: mdi:bomb

################################################
## Script
################################################

script:
  restart_mqtt:
    sequence:
      - service: shell_command.restart_mqtt

################################################
## Shell Command
################################################

shell_command:
  restart_mqtt: >-
    sudo /bin/systemctl restart mosquitto.service
