# HASS SSL Certificate expiration control
#
#

sensor:

# https://www.home-assistant.io/integrations/cert_expiry
# https://community.home-assistant.io/t/sensor-to-show-expiry-date-of-ssl-certificate/13479/66
#sensor:
  - platform: cert_expiry
    host: hellad.noip.me
    port: 88
    name: ssl_certificate_expiry


# Report IP changes
automation:
  - alias: update_entity_on_reboot
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "0:00:30"
      - service: homeassistant.update_entity
        entity_id: sensor.ssl_certificate_expiry
